name: Build Executables

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python -m venv .venv
      - run: .venv\Scripts\activate && pip install --upgrade pip
      - run: .venv\Scripts\activate && pip install -r requirements.txt pyinstaller
      - run: .venv\Scripts\activate && pyinstaller --onefile --windowed --name "BatchEmailSender" main.py
      - uses: actions/upload-artifact@v4
        with:
          name: BatchEmailSender-Windows
          path: dist/BatchEmailSender.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python3 -m venv .venv
      - run: source .venv/bin/activate && pip install --upgrade pip
      - run: source
